---

system_linux_dconf_distro:
  - path: "/org/gnome/shell"
    keys:
      enabled-extensions: "['GPaste@gnome-shell-extensions.gnome.org','background-logo@fedorahosted.org']"
      favorite-apps: "['org.gnome.Terminal.desktop','firefox.desktop','org.gnome.Nautilus.desktop','1password.desktop','org.gnome.gedit.desktop','signal-desktop.desktop']"

