---

tmux_clipboard: "wl-copy"

system_linux_dconf_distro:
  - path: "/org/gnome/desktop/interface"
    keys:
      gtk-theme: "'Yaru-light'"
  - path: "/org/gnome/shell"
    keys:
      disabled-extensions: "[\
        'ding@rastersoft.com',
        'window-list@gnome-shell-extensions.gcampax.github.com',
        'horizontal-workspaces@gnome-shell-extensions.gcampax.github.com',
        'places-menu@gnome-shell-extensions.gcampax.github.com',
        'ubuntu-dock@ubuntu.com',
        'workspace-indicator@gnome-shell-extensions.gcampax.github.com']"
      enabled-extensions: "[\
        'GPaste@gnome-shell-extensions.gnome.org',
        'launch-new-instance@gnome-shell-extensions.gcampax.github.com',
        'auto-move-windows@gnome-shell-extensions.gcampax.github.com',
        'ubuntu-appindicators@ubuntu.com']"
      favorite-apps: "[\
        'org.gnome.Terminal.desktop',
        'firefox_firefox.desktop',
        'org.gnome.Nautilus.desktop',
        '1password.desktop',
        'org.gnome.gedit.desktop',
        'org.signal.Signal.desktop']"


