#!/usr/bin/env sh
# shellcheck disable=SC1090,SC1091

set -o errexit

ANSIBLE_REPO_PATH="${HOME}/ansible.$(date +%H%M%S)"
ANSIBLE_REPO_BRANCH="main"
ANSIBLE_REPO_URL="https://github.com/bradleyfrank/ansible.git"

TMP_ROLEVARS="$(mktemp)"
TMP_OP_SESSION_FILE="${HOME}/.op_session"

export HOMEBREW_INSTALL_ON_LINUX=1
HOMEBREW_INSTALL_SCRIPT="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"


install_homebrew() {
  case "$ID" in
    fedora) sudo dnf install -y procps-ng file @development-tools ;;
    debian|ubuntu|linuxmint|pop) sudo apt-get install -y build-essential procps file ;;
    macos) sudo softwareupdate --install-rosetta ;;
  esac
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL $HOMEBREW_INSTALL_SCRIPT)"
}


bootstrap_mac() {
  pgrep caffeinate >/dev/null || (caffeinate -d -i -m -u &)
  export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"
  ID=macos install_homebrew
  brew install python3 git
}


bootstrap_linux() {
  sudo systemctl stop packagekit
  . /etc/os-release

  case "$ID" in
    fedora)
      sudo dnf clean all
      sudo dnf makecache
      sudo dnf install -y python3 python3-devel python3-pip python3-wheel gcc git redhat-lsb-core
      ;;
    debian|ubuntu|linuxmint|pop)
      sudo apt-get clean
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip python3-venv git lsb-release
      ;;
    *) exit 1 ;;
  esac

  if [ -n "$HOMEBREW_INSTALL_ON_LINUX" ]; then
    install_homebrew
  fi
}


while getopts ':hb:n' opt; do
  case "$opt" in
    h) echo "[-h] | [-n] [-b <branch>]"; exit 0 ;;
    b) ANSIBLE_REPO_BRANCH="$OPTARG" ;;
    n) unset HOMEBREW_INSTALL_ON_LINUX ;;
    *) exit 1 ;;
  esac
done

case $(uname -m) in (aarch*|arm*)
  unset HOMEBREW_INSTALL_ON_LINUX ;;
esac

case $(uname -s) in
  Darwin) bootstrap_mac ;;
  Linux)  bootstrap_linux ;;
  *)      exit 1 ;;
esac

git clone "$ANSIBLE_REPO_URL" "$ANSIBLE_REPO_PATH"
cd "$ANSIBLE_REPO_PATH" >/dev/null
git checkout "$ANSIBLE_REPO_BRANCH"

PATH="$(python3 -m site --user-base)/bin:${PATH}"; export PATH
python3 -m venv venv
. venv/bin/activate
pip install --no-cache-dir --requirement requirements.txt

grep "^(#|-|$)" roles/*/defaults/main.yml \
  --invert-match \
  --no-filename \
  --extended-regexp \
  --color=never \
  | sed "s/^/# /g" >> "$TMP_ROLEVARS"

vim -c "e ${TMP_ROLEVARS}|redraw|echom 'Save and quit to continue running the install script.'"

ansible-playbook playbooks/bootstrap_ansible.yml \
  --ask-become-pass \
  --tags "all,never" \
  --extra-vars "system_hostname=$(uname -n) role_vars=${TMP_ROLEVARS} user_id=$(id -un)"

# The 1Password session file exists if the GUI is not installed.
if [ -e "$TMP_OP_SESSION_FILE" ]; then
  . "$TMP_OP_SESSION_FILE"
  rm --force "$TMP_OP_SESSION_FILE"
fi

ansible-playbook playbooks/site.yml --ask-become-pass --tags "all,never"
