#!/usr/bin/env sh

set -o errexit

ANSIBLE_REPO_PATH="$HOME/ansible.$(date +%H%M%S)"
ANSIBLE_REPO_BRANCH=main
ANSIBLE_REPO_URL=https://github.com/bradleyfrank/ansible.git
ANSIBLE_TEMP_INVENTORY="$(mktemp)"
INSTALL_HOMEBREW_LINUX=true
HOMEBREW_INSTALL_SCRIPT=https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
VAULT_PASSWORD_FILE="$HOME/.ansible/vault"; export VAULT_PASSWORD_FILE

echo "localhost ansible_connection=local" > "$ANSIBLE_TEMP_INVENTORY"

install_homebrew() {
  case "$NAME" in
    Fedora*) sudo dnf install -y procps-ng file @development-tools ;;
    Ubuntu|LMDE) sudo apt-get install -y build-essential procps curl file ;;
    Darwin) sudo softwareupdate --install-rosetta ;;
  esac
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL $HOMEBREW_INSTALL_SCRIPT)"
}

bootstrap_mac() {
  pgrep caffeinate >/dev/null || (caffeinate -d -i -m -u &)
  export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"
  NAME=Darwin install_homebrew
  brew install python3 git
}

bootstrap_linux() {
  sudo systemctl stop packagekit
  # shellcheck disable=SC1091
  . /etc/os-release

  case "$NAME" in
    Fedora*)
      sudo dnf clean all
      sudo dnf makecache
      sudo dnf install -y python3 python3-devel python3-pip python3-wheel gcc git redhat-lsb-core
      ;;
    Debian*|Ubuntu|LMDE)
      sudo apt-get clean
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip git lsb-release
      ;;
    *) exit 1 ;;
  esac

  [ -n "$INSTALL_HOMEBREW_LINUX" ] && install_homebrew
}

while getopts ':bg:' opt; do
  case "$opt" in
    b) unset INSTALL_HOMEBREW_LINUX ;;
    g) ANSIBLE_REPO_BRANCH="$OPTARG" ;;
    *) exit 1 ;;
  esac
done

case $(uname -s) in
  Darwin) bootstrap_mac ;;
  Linux)  bootstrap_linux ;;
  *)      exit 1 ;;
esac

git clone "$ANSIBLE_REPO_URL" "$ANSIBLE_REPO_PATH"
cd "$ANSIBLE_REPO_PATH" >/dev/null
git checkout "$ANSIBLE_REPO_BRANCH"

PATH="$(python3 -m site --user-base)/bin:${PATH}"; export PATH
virtualenv venv
#shellcheck disable=SC1091
. venv/bin/activate
pip install --requirement requirements.txt

ansible-playbook playbooks/bootstrap.yml
ansible-playbook playbooks/site.yml --ask-become-pass
ansible-playbook playbooks/show_secrets.yml --extra_vars "delete_vault_file=true output_to_file=true"
