local builtin = require("telescope.builtin")
vim.keymap.set("n", "<C-n>", ":Telescope file_browser<CR>")
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>sp', builtin.spell_suggest, {})
vim.keymap.set('n', '<leader>gr', function()
    builtin.grep_string({search = vim.fn.input(":Grep > ")})
end)
