#!/usr/bin/env bash

#
# Creates a dicware passphrase with an equal-length random number at the end.
# Author: Brad Frank
# Date: Nov 2020
# Tested: GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.6.0)
# Requires: keepassxc-cli
#


# ----- functions ----- #

function make_numware() {
    local length dice word capital diceware=""
    length="$1"

    readarray -d " " -t dice < <( keepassxc-cli diceware --words "$length" )

    for word in "${dice[@]}"; do
        capital="$(printf "%s" "${word:0:1}" | tr '[:lower:]' '[:upper:]')"
        word="${word%$'\n'}" # remove newline
        diceware="${capital}${word:1}-${diceware}"
    done

    printf "%s%s\n" "$diceware" "$(keepassxc-cli generate -L "$length" -n)"
}


# ----- begin ----- #

if [[ -n "$1" ]]; then
  if [[ ! "$1" =~ ^[0-9]+$ || "$1" -lt 2 ]]; then
      echo "Length must be a value greater than 1."
      exit 1
  else
      make_numware "$1"
  fi
else
  make_numware 5
fi
