#!/usr/bin/env zsh

if type gcloud &> /dev/null; then
	project_id="$(gcloud config get-value project)"
	jq -r --arg PID "$project_id" '.[] | select(.projectId==$PID) | .name' \
		<(gcloud projects list --format json)
else
	echo "n/a"
fi
