#!/usr/bin/env zsh

if type kubectl &> /dev/null; then
    if context="$(kubectl config current-context 2> /dev/null)"; then
        echo "$context" | grep -o '[^_]*$'
    else
        echo "n/a"
    fi
else
    echo "n/a"
fi
