---

- name: "Stop packagekit"
  ansible.builtin.systemd:
    name: "packagekit"
    state: stopped
    enabled: false
  become: true
  notify: Start packagekit
  tags: [apt, dnf]

- name: "Add repositories (apt)"
  ansible.builtin.deb822_repository: "{{ item }}"
  loop: "{{ pkg_mgr_repos['base'] }}"
  loop_control:
    label: "{{ item['name'] }}"
  become: true
  when: pkg_mgr_repos['apt'] | length > 0
  tags: [apt]

- name: "Install gpg keys (dnf)"
  ansible.builtin.rpm_key:
    key: "{{ item['gpgkey'] }}"
    state: present
  loop: "{{ pkg_mgr_repos['base'] }}"
  loop_control:
    label: "{{ item['name'] }}"
  become: true
  when: pkg_mgr_repos['dnf'] | length > 0
  tags: [dnf]

- name: "Add repositories (dnf)"
  ansible.builtin.yum_repository: "{{ item }}"
  loop: "{{ pkg_mgr_repos['base'] }}"
  loop_control:
    label: "{{ item['name'] }}"
  become: true
  when: pkg_mgr_repos['dnf'] | length > 0
  tags: [dnf]

- name: "Update package manager cache"
  ansible.builtin.package:
    update_cache: true
  become: true
  tags: [apt, dnf]

- name: "Install cli packages"
  ansible.builtin.package:
    name: "{{ pkg_mgr_cli['base'] }}"
    state: present
  become: true
  tags: [apt, dnf]

- name: "Install gui packages"
  ansible.builtin.package:
    name: "{{ pkg_mgr_gui['common'] }}"
    state: present
  when: pkg_mgr_desktop_present
  become: true
  tags: [apt, dnf]

- name: "Install desktop packages"
  ansible.builtin.package:
    name: "{{ pkg_mgr_gui[pkg_mgr_current_desktop] }}"
    state: present
  when: "'pkg_mgr_current_desktop' in pkg_mgr_gui"
  become: true
  tags: [apt, dnf]

- name: "Include Homebrew tasks"
  ansible.builtin.include_tasks:
    file: "pkg_mgr/homebrew.yml"
  when: (ansible_facts['architecture'] == 'x86_64') or (ansible_facts['architecture'] == 'amd64')
  tags: [formulas]

- name: "Include Flakpak tasks"
  ansible.builtin.include_tasks:
    file: "pkg_mgr/flatpak.yml"
  when: pkg_mgr_desktop_present
  tags: [flatpak]
