---

- name: "Include vars"
  ansible.builtin.include_vars:
    file: "{{ lookup('ansible.builtin.first_found', global_vars_find) }}"

- name: "Include per-system tasks"
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts['system'] }}.yml"

- name: "Build `bat` cache"
  ansible.builtin.command:
    cmd: "{{ pkg_mgr_bat_exec }} cache --build"
  changed_when: true
