#!/usr/bin/env zsh

#
# Quickly setup a virtualenv for InfraCTL.
# Author: Brad Frank
# Date: Feb 2022
# Tested: zsh 5.8 (x86_64-apple-darwin19.6.0)
#

pinfractl() {
  [[ -n "$VIRTUAL_ENV" ]] && deactivate
  [[ -d ve ]] && rm -rf ve
  [[ -f .env ]] && rm .env
  virtualenv -p 3.8 ve
  source ./ve/bin/activate
  ./ve/bin/python -m pip install -r requirements.txt
  ./ve/bin/python setup.py install
  {   echo "KUBECONFIG=$HOME/.kube/config"
      echo "INFRACTL_HOME=$(git rev-parse --show-toplevel)"
      sed -e 's/export //g' -e 's/ /\n/g' < "$HOME"/.infractl/secrets
  } > .env
  export "$(xargs < .env)"
}
