#!/usr/bin/env sh

set -o errexit

ANSIBLE_REPO_PATH="$HOME/ansible.$(date +%H%M%S)"
ANSIBLE_REPO_BRANCH=main
ANSIBLE_REPO_PLAYBOOK=bootstrap
ANSIBLE_REPO_URL=https://github.com/bradleyfrank/ansible.git

bootstrap_mac() {
  pgrep caffeinate >/dev/null || (caffeinate -d -i -m -u &)
  sudo --validate  # reset `sudo` timeout to use Homebrew install in noninteractive mode
  CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  brew install python3 git
  case "$(uname -m)" in
    x86_64) python_user_base="$(/usr/local/bin/python3 -m site --user-base)" ;;
     arm64) python_user_base="$(/opt/homebrew/bin/python3 -m site --user-base)" ;;
  esac
  PATH="/usr/local/bin:${python_user_base}/bin:${PATH}"
  export PATH
}

bootstrap_linux() {
  sudo systemctl stop packagekit
  sudo dnf clean all
  sudo dnf makecache
  sudo dnf install -y python3 python3-pip python3-devel python-wheel git redhat-lsb-core
}

while getopts ':dg:' opt; do
  case "$opt" in
    d) ANSIBLE_REPO_PLAYBOOK=dotfiles ;;
    g) ANSIBLE_REPO_BRANCH="$OPTARG" ;;
    *) exit 1 ;;
  esac
done

if [ "$ANSIBLE_REPO_PLAYBOOK" = bootstrap ]; then
  case $(uname -s) in
    Darwin) bootstrap_mac ;;
    Linux)  bootstrap_linux ;;
    *)      exit 1 ;;
  esac
fi

git clone "$ANSIBLE_REPO_URL" "$ANSIBLE_REPO_PATH"
cd "$ANSIBLE_REPO_PATH" >/dev/null
git checkout "$ANSIBLE_REPO_BRANCH"

python3 -m pip install --user virtualenv
virtualenv venv
#shellcheck disable=SC1091
. venv/bin/activate
pip install --requirement setup/requirements.txt

ansible-galaxy collection install -r setup/requirements.yml
ANSIBLE_CONFIG=setup/setup.cfg ansible-playbook setup/site.yml \
  --extra-vars current_hostname="$(hostname -s)" --extra-vars current_email="$(id -un)@$(uname -n)"

case $ANSIBLE_REPO_PLAYBOOK in
  bootstrap) ansible-playbook --ask-become-pass playbooks/bootstrap.yml ;;
  dotfiles)  ansible-playbook playbooks/dotfiles.yml ;;
esac
