#!/usr/bin/env sh

set -o errexit

ANSIBLE_REPO_BRANCH=main
ANSIBLE_REPO_PLAYBOOK=bootstrap
ANSIBLE_REPO_URL=https://github.com/bradleyfrank/ansible.git
ANSIBLE_REPO_PATH="$(mktemp -d)"

bootstrap_mac() {
  pgrep caffeinate >/dev/null || (caffeinate -d -i -m -u &)
  CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  brew install python3 git
}

bootstrap_linux() {
  if env | grep -q XDG_SESSION_DESKTOP; then
    dconf write /org/gnome/desktop/session/idle-delay 'uint32 0'
    dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout "'nothing'"
  fi

  sudo systemctl stop packagekit
  # shellcheck disable=SC1091
  . /etc/os-release

  case "$NAME" in
    Fedora)
      sudo dnf clean all
      sudo dnf makecache
      sudo dnf install -y python3 python3-pip python-wheel git redhat-lsb-core
      ;;
    Ubuntu|Pop)
      sudo apt-get clean
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip git lsb-release
      ;;
    *) exit 1 ;;
  esac
}

while getopts ':dg:' opt; do
  case "$opt" in
    d) ANSIBLE_REPO_PLAYBOOK=dotfiles ;;
    g) ANSIBLE_REPO_BRANCH="$OPTARG" ;;
    *) exit 1 ;;
  esac
done

if [ "$ANSIBLE_REPO_PLAYBOOK" = bootstrap ]; then
  case $(uname -s) in
    Darwin) bootstrap_mac ;;
    Linux)  bootstrap_linux ;;
    *)      exit 1 ;;
  esac
fi

PATH="$PATH:$(python3 -m site --user-base)/bin"; export PATH
python3 -m pip install --user ansible docker github3.py

git clone "$ANSIBLE_REPO_URL" "$ANSIBLE_REPO_PATH"
cd "$ANSIBLE_REPO_PATH" >/dev/null
git checkout "$ANSIBLE_REPO_BRANCH"

ansible-galaxy collection install -r setup/requirements.yml
ANSIBLE_CONFIG=setup/setup.cfg ansible-playbook setup/site.yml \
  --extra-vars current_hostname="$(hostname -s)" --extra-vars current_email="$(id -un)@$(uname -n)"

case $ANSIBLE_REPO_PLAYBOOK in
  bootstrap) ansible-playbook --ask-become-pass playbooks/bootstrap.yml ;;
  dotfiles)  ansible-playbook playbooks/dotfiles.yml ;;
esac

rm -rf "$ANSIBLE_REPO_PATH"
